name: vaultnote
description: Cross-platform notes app with GitHub sync
version: 1.0.0+1
license: AGPL-3.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0
  path: ^1.9.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  flutter_staggered_grid_view: ^0.7.0
  flutter_markdown_plus: ^1.0.7
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  crypto: ^3.0.3
  local_auth: ^3.0.0
  appflowy_editor: ^6.2.0
  markdown: ^7.3.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  intl: ^0.20.2
  receive_sharing_intent: ^1.8.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    icon_path: "assets/icon.png"
  linux:
    generate: true
    icon_path: "assets/icon.png"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
